"""add hotel management tables

Revision ID: 3b4a25aa8d18
Revises: 6cb1475686a0
Create Date: 2026-03-15 14:59:04.627312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4a25aa8d18'
down_revision: Union[str, Sequence[str], None] = '6cb1475686a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_plan_blocked', sa.Boolean(), nullable=False),
    sa.Column('widget_config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_slug'), 'properties', ['slug'], unique=True)
    op.create_index(op.f('ix_properties_user_id'), 'properties', ['user_id'], unique=False)
    op.create_table('promotions',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_property_id'), 'promotions', ['property_id'], unique=False)
    op.create_table('rooms',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_property_id'), 'rooms', ['property_id'], unique=False)
    op.create_table('services',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_property_id'), 'services', ['property_id'], unique=False)
    op.create_table('room_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('override_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'date')
    )
    op.create_index(op.f('ix_room_availability_room_id'), 'room_availability', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_availability_room_id'), table_name='room_availability')
    op.drop_table('room_availability')
    op.drop_index(op.f('ix_services_property_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_rooms_property_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_promotions_property_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_properties_user_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_slug'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
