"""add_rentals_amenities_tables

Revision ID: 96e5f65ae4e8
Revises: d269d1374ea6
Create Date: 2026-03-16 01:45:17.067717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96e5f65ae4e8'
down_revision: Union[str, Sequence[str], None] = 'd269d1374ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenity_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('name', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('photos', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('daily_capacity', sa.Integer(), nullable=True),
    sa.Column('guest_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenity_items_property_id'), 'amenity_items', ['property_id'], unique=False)
    op.create_table('rental_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('name', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('photos', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('guest_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_items_property_id'), 'rental_items', ['property_id'], unique=False)
    op.create_table('amenity_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('amenity_item_id', sa.UUID(), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('room_booking_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['amenity_item_id'], ['amenity_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenity_bookings_amenity_item_id'), 'amenity_bookings', ['amenity_item_id'], unique=False)
    op.create_index(op.f('ix_amenity_bookings_date'), 'amenity_bookings', ['date'], unique=False)
    op.create_index(op.f('ix_amenity_bookings_property_id'), 'amenity_bookings', ['property_id'], unique=False)
    op.create_index(op.f('ix_amenity_bookings_stripe_payment_intent_id'), 'amenity_bookings', ['stripe_payment_intent_id'], unique=False)
    op.create_table('rental_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('rental_item_id', sa.UUID(), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('room_booking_id', sa.UUID(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_item_id'], ['rental_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_bookings_property_id'), 'rental_bookings', ['property_id'], unique=False)
    op.create_index(op.f('ix_rental_bookings_rental_item_id'), 'rental_bookings', ['rental_item_id'], unique=False)
    op.create_index(op.f('ix_rental_bookings_stripe_payment_intent_id'), 'rental_bookings', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_bookings_stripe_payment_intent_id'), table_name='rental_bookings')
    op.drop_index(op.f('ix_rental_bookings_rental_item_id'), table_name='rental_bookings')
    op.drop_index(op.f('ix_rental_bookings_property_id'), table_name='rental_bookings')
    op.drop_table('rental_bookings')
    op.drop_index(op.f('ix_amenity_bookings_stripe_payment_intent_id'), table_name='amenity_bookings')
    op.drop_index(op.f('ix_amenity_bookings_property_id'), table_name='amenity_bookings')
    op.drop_index(op.f('ix_amenity_bookings_date'), table_name='amenity_bookings')
    op.drop_index(op.f('ix_amenity_bookings_amenity_item_id'), table_name='amenity_bookings')
    op.drop_table('amenity_bookings')
    op.drop_index(op.f('ix_rental_items_property_id'), table_name='rental_items')
    op.drop_table('rental_items')
    op.drop_index(op.f('ix_amenity_items_property_id'), table_name='amenity_items')
    op.drop_table('amenity_items')
    # ### end Alembic commands ###
